services:
  finnhub:
    build: ./finnhub
    depends_on:
      - kafka
    environment:
      TICKER: AAPL
    restart: always

  twelvedata:
    build: ./twelvedata
    depends_on:
      - kafka
    environment:
      TICKER: AAPL
    restart: always

  stockdata:
    build: ./stockdata
    depends_on:
      - kafka
    environment:
      TICKER: AAPL
    restart: always

  kafka:
    image: 'bitnami/kafka'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka/data
    ports:
      - "9092:9092"
      - "9093:9093"
    restart: always

  prediction:
    build: ./prediction
    depends_on:
    - kafka
    env_file:
      - .env
    environment:
      - PYTHON UNBUFFERED=1
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "8080:8080"
    restart: always

  analytics:
    build: ./analytics
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    restart: always

  client:
    build: ./client
    depends_on:
      - analytics
    ports:
      - "5173:5173"
    restart: always

volumes:
  kafka-data:


