services:
  finnhub:
    build: ./finnhub
    depends_on:
      - kafka
    environment:
      TICKER: AAPL
  twelvedata:
    build: ./twelvedata
    depends_on:
      - kafka
    environment:
      TICKER: AAPL
  stockdata:
    build: ./stockdata
    depends_on:
      - kafka
    environment:
      TICKER: AAPL
  kafka:
    image: 'bitnami/kafka'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka/data
    ports:
      - "9092:9092"
      - "9093:9093"
  prediction:
    build: ./prediction
    depends_on:
    - kafka
    environment:
      - PYTHON UNBUFFERED=1
      - ALPHA_VANTAGE_API_KEY=K6QQP60C5DSXN8MU
      - DATABASE_PASSWORD=C0OZACjKnWMF4GQz
    ports:
      - "8080:8080"
  #analytics:
  #  build: analytics

volumes:
  kafka-data:


